baseURL: https://zq.lu/
languageCode: en-uk
title: zqlu - convenient public keys
theme: PaperMod
params:
  homeInfoParams:
    Title: "zqlu \U0001F510"
    Content: >
      zqlu is a text-based format for public keys. It is similar to the OpenSSH public key format, but
      the resulting keys are shorter, only contains easy to copy characters, and has a built-in checksum to detect
      corruption.

      Please use the javascript below to try it out, or have a look at the [reference implementation and
      specification](https://github.com/nresare/zqlu) for more information.
  socialIcons:
    - name: github
      url: "https://github.com/nresare/zqlu"

  author:
    name: Noa Resare
    email: noa@resare.com
    location: London

